---
- name: Clean apt packages
  shell: apt-get clean all

- name: Debian | Disable Services
  service: name={{ item }} state=stopped enabled=no
  with_items:
    #- ntp
    - dnsmasq
    - splunk
  ignore_errors: true

- name: Debian | Remove packages
  apt: name={{ item }} update_cache=yes state=absent
  with_items:
    - puppet
    - hiera
    - facter
    - puppetlabs-release
    - splunkforwarder
    # The only box we need alertlogic agent on is a CentOS box (Ops Logstash)
    - al-agent
    # Exists on some Debian/Ubuntu GCE boxes
    - sshguard

- name: Debian | Install common packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - iptables
    - htop
    - jq
    - haveged
    - python-pip
    # This is needed to be able to curl from ansible
    - python-httplib2
    - tcpdump
    - dnsutils
    - iptraf-ng
    - vim
    - rsyslog

- name: RedHat | Start services
  service: name={{ item }} state=running enabled=yes
  with_items:
    - haveged
    - rsyslog
